version: "2"
networks:
  net:

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
  backend:
    build:
      context: backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - net
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/app
    networks:
      - net
